services:
    wdherndon.wordcount.listener:
        class: wdherndon\wordcount\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
